spring.application.name=sidequest
spring.datasource.url=jdbc:postgresql://localhost:5432/side_quest_db
spring.datasource.username=jsakoman
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
